# Publishes a tag/branch to Composer Packages of the current project
publish:
  image: ${CI_DEPENDENCY_PROXY_DIRECT_GROUP_IMAGE_PREFIX}/curlimages/curl:latest
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG != null'
      variables:
        COMMIT_REF_KEY: 'tag'
    - if: '$CI_COMMIT_TAG == null'
      variables:
        COMMIT_REF_KEY: 'branch'
  script:
    - apk add curl
    - 'curl --fail-with-body --header "Job-Token: $CI_JOB_TOKEN" --data $COMMIT_REF_KEY=$CI_COMMIT_REF_NAME "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'